on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker
      run: docker login -u sivashankaar1998@gmail.com -p pwd
    - name: Build the Docker images
      run: docker build . -t sivashankaar1998/pipeline
    - name: Push image
      run: docker push sivashankaar1998/pipeline
